### ISSUE TITLE
Is there a way to edit the time between starting craft and pressing the first macro?

### ISSUE THREAD

**Issue by nikolovjd** [Saad888/AutoSynthesis#1]
Sometimes the delay between "synthetize" and the craft window appearing is too long, which causes the 1st macro to fail.

**Comment by Saad888** [comment]
I'll investigate this and see if I can add an option to add extra time, but could you take a video or recording of this happening just for reference?

**Comment by Saad888** [comment]
New release created to add this option
https://github.com/Saad888/AutoSynthesis/releases/tag/1.1
