### ISSUE TITLE
Craft complete notification

### ISSUE THREAD

**Issue by GsynthChris** [Saad888/AutoSynthesis#13]
Hey, love the app! Thanks so much for your hard work on this!

I know you aren't planning on adding any new features any time soon, but if the day comes when you do, something that would be cool is to add a craft complete notification. For instance, after you complete your craft count, the app will play a windows sound.

**Comment by Saad888** [comment]
Sorry I missed this before! I'll add it to a list of features to eventually address but at this rate I don't think I'll be updating the app
