### ISSUE TITLE
only crafting 1 item 

### ISSUE THREAD

**Issue by KaiserAzura** [Saad888/AutoSynthesis#16]
ok so I'm not to sure what I'm doing wrong but everything seems to work fine until the first item finishes and then it just keep pressing the macros like its trying to make the next  item over again but it doesn't start the next item to craft just continues to hit the macros. 
(i have double checked to make sure confirm and cancel are both set properly).

**Comment by SaadTaimoor-TFD** [comment]
What are your keybinds for Cancel and Confirm in the game?
