### ISSUE TITLE
It's not doing my game input

### ISSUE THREAD

**Issue by Royalaaa** [Saad888/AutoSynthesis#18]
[ERROR.txt](https://github.com/Saad888/AutoSynthesis/files/9491157/ERROR.txt)

**Comment by Saad888** [comment]
Are you using xiv Alexander w/ it?

**Comment by Royalaaa** [comment]
Yes, I disabled xiv alexander and its working again, thx♥

**Comment by Saad888** [comment]
Perfect! If you want an alternative which works with autosynth you can try noclippy: https://github.com/UnknownX7/NoClippy
