### ISSUE TITLE
Doesn't select new craft

### ISSUE THREAD

**Issue by Rafriot** [Saad888/AutoSynthesis#2]
New update seems to have broken something, instead of selecting the big yellow button on second auto craft, it goes to the middle menu and selects the food item instead and the second craft just doesn't happen...I worked around it by having the 3rd macro do a second Confirm button so it'll start the second properly.

Edit: I realised that I was using the older version, but I cannot for the life of me figure out how to install the new update. It just says "Unable to locate application file 'Setup1.msi'." when I try to run the .exe and I can't run anything from the AutoSynthesis1.1 folder...

**Comment by SaadTaimoorTR** [comment]
I'll fix the installation

**Comment by Saad888** [comment]
I've fixed the installation, should work now.

Please let me know if you are still running into this issue

**Comment by Rafriot** [comment]
Seems to be fixed now, able to install and queue multiple crafts. Thank you for this, it's a very neat program that's simple enough to use!!

**Comment by Saad888** [comment]
Perfect, thanks for your support and help!
