### ISSUE TITLE
Inputs aren't sending

### ISSUE THREAD

**Issue by Annon9007723** [Saad888/AutoSynthesis#23]
Trying to mess around with the different settings in there, but even when default it looks like it's not working. I can't tell if it's one of the existing plugins being fussy and preventing it from being used, but there might need to be some more testing.

**Comment by Annon9007723** [comment]
So slight update, for some reason there's two of these. Not sure why, but I think this might be my problem. So...my bad about making this. Going to close the issue report if I remove the duplicate. 
![image](https://user-images.githubusercontent.com/26782997/214522564-2bae2f69-134d-4efc-9bea-7d398558192d.png)

**Comment by Annon9007723** [comment]
So, two things. One, it does work. Make sure you double check to see if you have a duplicate task running for XIV. Because if you do it can be caught by...literally everything. ACT, Teamcraft, all of it. Only way I found to get rid of it would be rebooting the computer.

Second thing, use single buttons for the macros. Don't do things like Shift+C and expect it to work 100% of the time.

**Comment by Saad888** [comment]
I've usually run it with multiple copies of FFXIV open and in my experience the app defaults to the latest active process, I don't have logic in place to let you select the instance but it should work.

As for modifiers yeah it is better to avoid them as they can cause conflicts with other inputs and applications running.
