### ISSUE TITLE
Adding some seconds to the macro time

### ISSUE THREAD

**Issue by username4447** [Saad888/AutoSynthesis#24]
Maybe that's me but I always have to add 7 seconds to what teamcraft says, should I set the "delay before starting a craft" to 7 ?

**Comment by Saad888** [comment]
I'm not sure how teamcraft is calculating their macro times but you can count the total time of the macro in the <wait.X> statements, or add your macros into this window here to see the total time:
https://ffiv-macro-timer-saad888.vercel.app/
