### ISSUE TITLE
The "preparing next craft" step doesn't quite work right.

### ISSUE THREAD

**Issue by coredumperror** [Saad888/AutoSynthesis#25]
When I use AutoSynthesis, after the first craft finishes, it claims to be "preparing next craft" by sending `NUM 0` three times, but it fails to do so. It then runs the macro again, with no craft active, and then the next time "preparing next craft" occurs, it works correctly, begins the craft, and then the macro runs properly. This issue repeats for every craft, with only every _other_ macro execution actually crafting an item.

I'm guessing that it's sending those 3 `NUM 0` keys to prep the next craft just a little bit too early, so the game isn't picking them up.

Setting the Delay before starting a Craft doesn't help, because that adds more time *after* the `NUM 0`s, rather than before.

**Comment by Saad888** [comment]
Could you try adding more time to the end of your last macro and see if
that helps?

**Comment by coredumperror** [comment]
Unfortunately, that didn't do anything.

Taking a closer look at what AutoSynthesis is doing, it seems to be sending the three `NUM 0`s before the Crafting Log has re-opened after the craft was finished. That's why it fails to start on the next craft, but works on the one after that.

Just in case it's helpful, I'm using the hotkey Ctrl+Alt+1 for my macro, and the macro is:

```
/ac "Trained Eye" <wait.3>
/ac "Groundwork" <wait.3>
/echo 'Craft finished! <se.2>
```

I'm making Super-Ethers for sale on the MB. 

I tried adding `<wait.4>` to the echo, but that didn't help. I tried making the wait after Groundwork longer, but that also didn't help.

**Comment by coredumperror** [comment]
Ohhhhh, I figured it out! I had completely missed the "Macro Time (sec)" column in the settings, and was using the default of 5 seconds. Since my macro happens to be only *6 seconds*, I was simply misinterpreting what I was seeing as a bug, rather than an obvious configuration problem.

**Comment by Saad888** [comment]
Gotcha glad it worked!
