### ISSUE TITLE
When finishing a craft it opens the free company window and never begins the second craft

### ISSUE THREAD

**Issue by LoonMasterFlex** [Saad888/AutoSynthesis#26]
Not sure what is going on here... I'm usually a controller player so all my keyboard binds should be the defaults.
Yes I have the game set to mouse and keyboard while tying this.

Set it up per the instructions, hit Start.
First craft begins as expected.
First craft ends.
Free company window opens, gets stuck.

**Comment by LoonMasterFlex** [comment]
ok I got it to stop opening free company, buit now it only is able to craft one item per 2 loops it tries.

**Comment by Saad888** [comment]
Can you confirm if the timings you've entered for your macro are correct?

**Comment by LoonMasterFlex** [comment]
lol wow, that was it, it was 1 second too quick.
My bad lmao

Cheers!

**Comment by Saad888** [comment]
No prob! Glad it worked!
