### ISSUE TITLE
Feature Request - Time to Complete

### ISSUE THREAD

**Issue by squishey123** [Saad888/AutoSynthesis#4]
**Just an idea for an additional feature for AutoSynthesis:**
A 4th progress bar that counts up/down to the end of the whole crafting batch, taking into account not just the raw crafting time but also the time for food refreshes if selected, the delay added in the settings menu, and the extra time used for finishing a collectible craft if selected.

**Alternative:**
Time remaining posted in the black info box on the bottom right corner using the time calculation mentioned above

**Use case:**
Using the time remaining to judge how much time you have to do something else until you need to jump back into the game, such as making dinner while a crafting batch is going but not wanting to waste precious minutes sitting idle

_Love the tool and really appreciate the hard work put into it!_

**Comment by Saad888** [comment]
Currently, rolling updates are disabled, I'll create an update in Endwalker with this and a few other features once I have the time
