### ISSUE TITLE
Feature Request - AutoRepair

### ISSUE THREAD

**Issue by squishey123** [Saad888/AutoSynthesis#5]
**Attempt to repair equipment after X crafting operations:**
The user would add the repair action to their Hotbar and after X crafts (Configurable in the settings menu) AutoSynthesis would open the repair menu and repair any equipment below 100% (By just hitting the repair all button). Intervals could just be an entry box or a drop-down menu with intervals such as every 50, 75, 100, 125, 150, 175, or 200 crafts with the default being Disabled.

**Optional:**
A check box within the settings menu to attempt a repair after first craft in case the user's equipment was already at a fairly low durability as to not fail any crafts before the selected interval had been hit.

**Use case:**
Let's say for example I was to set up AutoSynthesis to do 200 crafting operations for smoked chicken. By the time I hit about 100 crafts even if I had repaired all my equipment before the first craft there is a high chance things such as jewelry will be close to breaking, which in turn would reduce max CP and likely fail subsequent crafts. Having the equipment repaired every 50-100 crafts would prevent this from happening and allow the user to queue up more crafts to be done in a row without user intervention.

_Thanks for taking the time to read through as well as all the work put into Autosynthesis up until this point!_

**Comment by Shugg1214** [comment]
Would love this! planning to use this script for some mindlessness and gunna be at my desk anyway but autorepair would just be so convenient, whether it targets an npc for it, or navigates the character interface to repair using dark matter from the inventory, i'd be happy with either, whatever is easier to implement.

**Comment by Saad888** [comment]
I'll add this to a list of potential features to add down the line. Currently, I don't intend to make any new updates until 6.0 as I don't have rolling updates enabled, but once EW is out I'll look into adding something like this
