### ISSUE TITLE
Any chance for support for Mac CrossOver bottles? 

### ISSUE THREAD

**Issue by danlavelle** [Saad888/AutoSynthesis#7]
Currently the MSI will install into a CrossOver bottle but crashes on startup. I was wondering if you were planning any support or debugging the existing issues. I can grab logs if that's helpful.

**Comment by danlavelle** [comment]
[autosynthesis_crash_log.txt](https://github.com/Saad888/AutoSynthesis/files/7548365/autosynthesis_crash_log.txt)
May or may not be helpful :) I'm also asking on the Mod Support github: https://github.com/seathasky/FF14-MAC_ModSupport

**Comment by Saad888** [comment]
Unfortunately I don't have a Mac or any way to properly test this
currently, or the time atm. I might be able to look into it sometime in the
new year, especially if the app breaks on Endwalker

**Comment by danlavelle** [comment]
Thanks! Happy to test if you do 😊
