### ISSUE TITLE
6.0 Endwalker

### ISSUE THREAD

**Issue by g-iori** [Saad888/AutoSynthesis#8]
Any updates needed for 6.0 or is it still working?

**Comment by Saad888** [comment]
Still works as far as my testing has gone

**Comment by astrayaa** [comment]
ive just tested on endwalker expansion. im having problems crafting more then 1 item at time. it stops at 1.

**Comment by Saad888** [comment]
Can you please share additional details, I've not been able to replicate this issue

**Comment by astrayaa** [comment]
its working. the issue was an input error on my end thanks

**Comment by nightmoon1996** [comment]
after 500+ synthesis no error so far

**Comment by Saad888** [comment]
Thanks for confirming!
